// Bots

import { Mongo } from 'meteor/mongo';
import { SimpleSchema } from 'meteor/aldeed:simple-schema';

if(Meteor.isServer){
  import { Restivus } from 'meteor/nimble:restivus';
}

// collection and schema

export const Bots = new Mongo.Collection('bots');

let botSchema = new SimpleSchema({
  organizationId: {
    type: String,
    label: "Organization ID for BallotBot"
  },
  electionId: {
    type: String,
    label: "Election ID for BallotBot"
  },
  stationId: {
    type: String,
    label: "Station ID of BallotBot"
  },
  botType: {
    type: String,
    label: "Type of BallotBot"
  },
  token: {
    type: String,
    label: "Auth token for BallotBot, generated by server"
  },
  serialNumber: {
    type: Number,
    label: "Serial Number of BallotBot",
    optional: true
  }

});

Bots.attachSchema(botSchema);

// collection hooks




// collection API
